name: AI-driven Web-based Ancillary Lab Assistant | UNO Q & Gemini
description: Based on Arduino UNO Q, this lab assistant is able to show real-time sensor readings, identify users by fingerprint, detect lab equipment via object detection, generate AI lessons via Gemini, and talk through its full-fledged web dashboard.
ports: []
bricks:
- arduino:web_ui: {}
- arduino:dbstorage_sqlstore: {}
- arduino:video_object_detection:
    model: yolox-object-detection
- arduino:cloud_llm: {}
icon: 🔬
